### ISSUE TITLE
when I run"python main.py fullobs_collect_treasure dir_1",there are the errors

### ISSUE THREAD

**Issue by Gezx** [shariqiqbal2810/MAAC#13]
Episodes 1-13 of 50000
Process Process-1:
Traceback (most recent call last):
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gezhixin/MAAC-master/utils/env_wrappers.py", line 20, in worker
    ob = env.reset()
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/gym/core.py", line 66, in reset
    raise NotImplementedError
NotImplementedError
Process Process-2:
Traceback (most recent call last):
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gezhixin/MAAC-master/utils/env_wrappers.py", line 20, in worker
    ob = env.reset()
  File "/home/gezhixin/anaconda3/lib/python3.6/site-packages/gym/core.py", line 66, in reset
    raise NotImplementedError
NotImplementedError
Process Process-3:

**Comment by shariqiqbal2810** [comment]
Make sure your package versions match what is specified in the README (specifically gym in this case)
